### ISSUE TITLE
need a method to stop socks5 server

### ISSUE THREAD

**Issue by 86chenjie** [LacticWhale/socks_dart#11]
I didn't find a way to stop socks5 server.

**Comment by LacticWhale** [comment]
I will look at it ASAP.

**Comment by LacticWhale** [comment]
`SocksServer` has exposed `proxies` field which store all proxy servers bound to `SocksServer` you can close server from it. 

I will add methods `SocksServer.close(int port)` and `SocksServer.closeAll()` in next release.

**Comment by LacticWhale** [comment]
Complited in #12
